#!/usr/bin/env python

import sys

from model import *
from analyzer import *

a = Analyzer(sys.argv[1])

a.DumpDot(sys.stdout)
a.PostProcess()
a.DumpDot(sys.stdout)

for n in a.nodes:
    print(n.Name(), n.trip_count)